import React, { useState, useEffect } from 'react';
import { 
  Activity, 
  AlertTriangle, 
  ShieldCheck, 
  Camera, 
  Stethoscope, 
  RefreshCw, 
  CheckCircle2, 
  User, 
  Eye, 
  ArrowRight, 
  UploadCloud, 
  Layers, 
  Clock, 
  MapPin, 
  FileText, 
  AlertCircle, 
  Server, 
  Cpu, 
  Check, 
  X, 
  ChevronRight,
  Info,
  Sliders,
  ExternalLink,
  Zap
} from 'lucide-react';

const API_BASE = '/api';

const DEMO_CASES = {
  anomaly: {
    title: "Flock Inactivity & Huddling (High Risk)",
    previousImage: "/demo/healthy_flock.jpg",
    currentImage: "/demo/concerning_flock.jpg",
    result: {
      summary: "Significant increase in bird clustering near heat sources with localized lethargy observed.",
      observations: [
        { title: "Reduced Flock Activity", description: "At least 14 visible birds remain stationary and lethargic compared to baseline.", severity: "high" },
        { title: "Tight Huddling Pattern", description: "Abnormal density grouping detected in southwest corner of enclosure.", severity: "high" },
        { title: "Slight Wing Drooping", description: "Isolated instances of drooped postures observed in foreground specimens.", severity: "medium" }
      ],
      risk_level: "HIGH",
      evidence: [
        "Increased clustering (+65% density in corner)",
        "Reduced visible movement compared to reference",
        "Multiple stationary birds in uncharacteristic posture"
      ],
      recommended_action: "Immediately isolate affected enclosure zone. Initiate temperature audit and contact veterinarian for urgent on-site inspection.",
      uncertainty: "Gemma 4 visual analysis only. Physical palpation, temperature, and lab sampling are required for clinical confirmation."
    }
  },
  healthy: {
    title: "Normal Active Feeding Behavior (Low Risk)",
    previousImage: "/demo/healthy_flock.jpg",
    currentImage: "/demo/moderate_flock.jpg",
    result: {
      summary: "Flock demonstrates normal movement distribution, active foraging, and alert body posture.",
      observations: [
        { title: "Uniform Dispersion", description: "Birds are evenly distributed across the feeding and watering zones.", severity: "low" },
        { title: "Alert Posture", description: "Head elevation and movement velocities align with healthy baseline metrics.", severity: "low" }
      ],
      risk_level: "LOW",
      evidence: [
        "Consistent spatial distribution",
        "Normal active behavior at waterers",
        "Zero abnormal clustering detected"
      ],
      recommended_action: "Maintain standard flock management, temperature controls, and biosecurity protocols.",
      uncertainty: "Visual monitoring report generated by Gemma 4 12B. Routine physical checks should be maintained."
    }
  }
};

/**
 * Helper: fetch an image URL and return a File object for FormData upload
 */
async function urlToFile(url, filename) {
  const res = await fetch(url);
  const blob = await res.blob();
  return new File([blob], filename, { type: blob.type });
}

export default function App() {
  // Global State management
  const [role, setRole] = useState('farmer'); // 'farmer' | 'vet'
  const [comparisonMode, setComparisonMode] = useState(true); // true = Compare, false = Single
  const [prevImage, setPrevImage] = useState(null);       // preview URL (string)
  const [currImage, setCurrImage] = useState(null);       // preview URL (string)
  const [prevFile, setPrevFile] = useState(null);          // File object for API
  const [currFile, setCurrFile] = useState(null);          // File object for API
  const [analyzing, setAnalyzing] = useState(false);
  const [analysisStep, setAnalysisStep] = useState(0);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const abortControllerRef = React.useRef(null);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [alerts, setAlerts] = useState([
    {
      id: "ALT-8921",
      farmId: "Barn #4 - North Wing",
      location: "Sector B7, Iowa Agri-Zone",
      timestamp: "10 minutes ago",
      riskLevel: "HIGH",
      summary: "Abnormal huddling & stationary posture detected in 18% of flock.",
      observations: ["Reduced movement", "Abnormal huddling near waterer"],
      evidence: ["+65% density grouping", "14 stationary birds detected"],
      status: "PENDING", // 'PENDING' | 'DISPATCHED' | 'DISMISSED'
      prevImg: "/demo/healthy_flock.jpg",
      currImg: "/demo/concerning_flock.jpg"
    }
  ]);
  const [dispatchedAlert, setDispatchedAlert] = useState(null);
  const [useBackendAPI, setUseBackendAPI] = useState(true);
  const [backendStatus, setBackendStatus] = useState("checking");

  // Check backend health on mount
  useEffect(() => {
    const checkBackend = async () => {
      try {
        const res = await fetch(`${API_BASE}/health`);
        if (res.ok) {
          const data = await res.json();
          if (data.ai?.ollama_running && data.ai?.gemma4_available) {
            setBackendStatus("connected");
            setUseBackendAPI(true);
          } else {
            setBackendStatus("no-gemma");
          }
        } else {
          setBackendStatus("disconnected");
        }
      } catch {
        setBackendStatus("disconnected");
        setUseBackendAPI(false);
      }
    };
    checkBackend();
    const interval = setInterval(checkBackend, 30000);
    return () => clearInterval(interval);
  }, []);

  // Synchronize dispatched alert state across roles
  useEffect(() => {
    const activeDispatch = alerts.find(a => a.status === 'DISPATCHED');
    if (activeDispatch) {
      setDispatchedAlert(activeDispatch);
    }
  }, [alerts]);

  // Poll backend alerts for vet dispatch status (farmer sees updates)
  useEffect(() => {
    if (!useBackendAPI) return;
    const interval = setInterval(async () => {
      try {
        const res = await fetch(`${API_BASE}/alerts`);
        if (res.ok) {
          const backendAlerts = await res.json();
          // Update local alerts with backend dispatch status
          if (backendAlerts.length > 0) {
            const dispatched = backendAlerts.find(a => a.status === 'vet_dispatched');
            if (dispatched) {
              setDispatchedAlert({
                id: dispatched.id,
                farmId: dispatched.farm_id,
                status: 'DISPATCHED'
              });
            }
          }
        }
      } catch { /* ignore */ }
    }, 5000);
    return () => clearInterval(interval);
  }, [useBackendAPI]);

  const skipToDemoResult = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }
    const defaultResult = (currImage && currImage.includes('healthy')) 
      ? DEMO_CASES.healthy.result 
      : DEMO_CASES.anomaly.result;
    setAnalysisStep(4);
    setAnalysisResult(defaultResult);
    setAnalyzing(false);
  };

  const runAnalysis = async (forceDemo = false) => {
    if (!currImage) return;

    setAnalyzing(true);
    setAnalysisStep(1);
    setAnalysisResult(null);
    setElapsedSeconds(0);

    const startTime = Date.now();
    const intervalTimer = setInterval(() => {
      setElapsedSeconds(Math.floor((Date.now() - startTime) / 1000));
    }, 500);

    let cancelled = false;
    const animateSteps = async () => {
      const delays = [800, 2500, 4500, 7000];
      for (let i = 0; i < delays.length && !cancelled; i++) {
        await new Promise(r => setTimeout(r, i === 0 ? delays[0] : delays[i] - delays[i - 1]));
        if (!cancelled) setAnalysisStep(i + 1);
      }
      while (!cancelled) {
        await new Promise(r => setTimeout(r, 2000));
        if (!cancelled) setAnalysisStep((s) => (s === 2 ? 3 : 2));
      }
    };
    animateSteps();

    // Fast demo mode (either explicitly chosen or backend disabled)
    if (forceDemo || !useBackendAPI) {
      await new Promise(r => setTimeout(r, 1000));
      cancelled = true;
      clearInterval(intervalTimer);
      setAnalysisStep(4);
      const res = (currImage && currImage.includes('healthy')) ? DEMO_CASES.healthy.result : DEMO_CASES.anomaly.result;
      setAnalysisResult(res);
      setAnalyzing(false);
      return;
    }

    // Live Ollama Gemma 4 inference
    try {
      let fileToSend = currFile;
      if (!fileToSend && currImage) {
        fileToSend = await urlToFile(currImage, 'current.jpg');
      }

      let prevToSend = prevFile;
      if (!prevToSend && prevImage) {
        prevToSend = await urlToFile(prevImage, 'previous.jpg');
      }

      const controller = new AbortController();
      abortControllerRef.current = controller;
      const timeoutId = setTimeout(() => controller.abort(), 120000); // 2 min safety timeout

      const formData = new FormData();
      let response;

      if (comparisonMode && prevToSend && fileToSend) {
        formData.append('previous', prevToSend);
        formData.append('current', fileToSend);
        response = await fetch(`${API_BASE}/compare`, { 
          method: 'POST', 
          body: formData,
          signal: controller.signal 
        });
      } else if (fileToSend) {
        formData.append('image', fileToSend);
        response = await fetch(`${API_BASE}/analyze`, { 
          method: 'POST', 
          body: formData,
          signal: controller.signal 
        });
      }

      clearTimeout(timeoutId);

      if (response && response.ok) {
        const data = await response.json();
        cancelled = true;
        clearInterval(intervalTimer);
        setAnalysisStep(4);
        await new Promise(r => setTimeout(r, 300));
        setAnalysisResult(data);
        setAnalyzing(false);
        return;
      }
    } catch (err) {
      console.warn("Backend error or cancelled:", err);
    }

    // Fallback to demo result if backend failed or timed out
    cancelled = true;
    clearInterval(intervalTimer);
    setAnalysisStep(4);
    const fallbackRes = (currImage && currImage.includes('healthy')) ? DEMO_CASES.healthy.result : DEMO_CASES.anomaly.result;
    setAnalysisResult(fallbackRes);
    setAnalyzing(false);
  };

  const loadDemo = async (caseKey) => {
    const demo = DEMO_CASES[caseKey];
    setPrevImage(demo.previousImage);
    setCurrImage(demo.currentImage);
    setComparisonMode(true);
    setAnalysisResult(demo.result);

    // Also prepare File objects for backend API
    try {
      const [prev, curr] = await Promise.all([
        urlToFile(demo.previousImage, 'previous.jpg'),
        urlToFile(demo.currentImage, 'current.jpg'),
      ]);
      setPrevFile(prev);
      setCurrFile(curr);
    } catch {
      // Files will be null — backend calls will fall back to demo
    }
  };

  const triggerVetAlert = async () => {
    if (!analysisResult) return;
    const newAlert = {
      id: `ALT-${Math.floor(1000 + Math.random() * 9000)}`,
      farmId: "Flock #A17 - Main Shelter",
      location: "Gemma Local Node #01",
      timestamp: "Just now",
      riskLevel: analysisResult.risk_level,
      summary: analysisResult.summary,
      observations: analysisResult.observations.map(o => o.title),
      evidence: analysisResult.evidence,
      status: "PENDING",
      prevImg: prevImage || "/demo/healthy_flock.jpg",
      currImg: currImage || "/demo/concerning_flock.jpg"
    };

    setAlerts([newAlert, ...alerts]);

    // Also push to backend if connected
    if (useBackendAPI) {
      try {
        await fetch(`${API_BASE}/alerts`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            farm_id: 'A17',
            risk_level: analysisResult.risk_level,
            summary: analysisResult.summary,
            observations: analysisResult.observations,
            evidence: analysisResult.evidence,
            recommended_action: analysisResult.recommended_action,
          })
        });
      } catch {
        // Alert stored locally even if backend fails
      }
    }
  };

  const handleAlertAction = async (id, newStatus) => {
    setAlerts(alerts.map(a => a.id === id ? { ...a, status: newStatus } : a));
    if (newStatus === 'DISPATCHED') {
      const target = alerts.find(a => a.id === id);
      setDispatchedAlert(target);
    }

    // Also update backend alerts
    if (useBackendAPI) {
      try {
        // Fetch backend alerts and update matching ones
        const res = await fetch(`${API_BASE}/alerts`);
        if (res.ok) {
          const backendAlerts = await res.json();
          for (const ba of backendAlerts) {
            if (ba.status === 'pending' && newStatus === 'DISPATCHED') {
              await fetch(`${API_BASE}/alerts/${ba.id}`, {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ status: 'vet_dispatched' })
              });
            }
          }
        }
      } catch { /* ignore */ }
    }
  };

  const handlePrevFileUpload = (e) => {
    if (e.target.files?.[0]) {
      const file = e.target.files[0];
      setPrevFile(file);
      setPrevImage(URL.createObjectURL(file));
    }
  };

  const handleCurrFileUpload = (e) => {
    if (e.target.files?.[0]) {
      const file = e.target.files[0];
      setCurrFile(file);
      setCurrImage(URL.createObjectURL(file));
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans antialiased flex flex-col selection:bg-emerald-500 selection:text-white">
      {/* Top Application Navigation Bar */}
      <header className="bg-slate-900 text-white border-b border-slate-800 sticky top-0 z-50 shadow-md">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          {/* Brand Logo & Local AI Badge */}
          <div className="flex items-center space-x-4">
            <div className="flex items-center space-x-2">
              <div className="w-10 h-10 rounded-xl bg-emerald-600 flex items-center justify-center text-white shadow-lg shadow-emerald-900/40">
                <ShieldCheck className="w-6 h-6" />
              </div>
              <div>
                <span className="font-bold text-lg tracking-tight text-white flex items-center gap-2">
                  FlockGuard
                  <span className="text-[10px] uppercase font-semibold bg-emerald-900/80 text-emerald-300 px-2 py-0.5 rounded-full border border-emerald-700/50">
                    MVP
                  </span>
                </span>
                <p className="text-xs text-slate-400 font-medium">Local AI Livestock Early-Warning</p>
              </div>
            </div>

            {/* Local Engine Status Tag */}
            <div className="hidden md:flex items-center space-x-2 bg-slate-800/90 border border-slate-700/80 px-3 py-1.5 rounded-lg text-xs">
              <Cpu className="w-4 h-4 text-emerald-400 animate-pulse" />
              <span className="text-slate-300 font-mono font-medium">Gemma 4 12B</span>
              <span className="text-slate-600">•</span>
              <span className="inline-flex items-center text-emerald-400 font-medium">
                <span className={`w-1.5 h-1.5 rounded-full mr-1.5 ${backendStatus === 'connected' ? 'bg-emerald-400 animate-ping' : 'bg-amber-400'}`}></span>
                {backendStatus === 'connected' ? 'Ollama Local' : backendStatus === 'checking' ? 'Checking...' : 'Offline'}
              </span>
            </div>
          </div>

          {/* Right Bar Controls & Role Switcher */}
          <div className="flex items-center space-x-3">
            {/* Backend Toggle */}
            <button 
              onClick={() => setUseBackendAPI(!useBackendAPI)}
              title="Toggle between demo engine and live Ollama backend API"
              className={`hidden sm:flex items-center space-x-1.5 px-2.5 py-1.5 rounded-lg text-xs font-medium border transition-colors ${
                useBackendAPI 
                  ? 'bg-amber-950/40 border-amber-600/50 text-amber-300' 
                  : 'bg-slate-800 border-slate-700 text-slate-400 hover:text-slate-200'
              }`}
            >
              <Server className="w-3.5 h-3.5" />
              <span>{useBackendAPI ? 'API: Live Gemma' : 'Demo Engine'}</span>
            </button>

            {/* Role Switcher Toggle */}
            <div className="bg-slate-800 p-1 rounded-xl border border-slate-700/80 flex items-center shadow-inner">
              <button
                onClick={() => setRole('farmer')}
                className={`flex items-center space-x-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all duration-150 ${
                  role === 'farmer'
                    ? 'bg-emerald-600 text-white shadow-md'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <User className="w-3.5 h-3.5" />
                <span>Farmer</span>
              </button>
              <button
                onClick={() => setRole('vet')}
                className={`flex items-center space-x-2 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all duration-150 relative ${
                  role === 'vet'
                    ? 'bg-emerald-600 text-white shadow-md'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Stethoscope className="w-3.5 h-3.5" />
                <span>Veterinarian</span>
                {alerts.filter(a => a.status === 'PENDING').length > 0 && (
                  <span className="w-2 h-2 rounded-full bg-red-500 absolute -top-0.5 -right-0.5"></span>
                )}
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Dispatched Vet Banner Notification */}
      {dispatchedAlert && (
        <div className="bg-emerald-900 border-b border-emerald-700 text-emerald-100 px-4 py-2.5 text-xs font-medium">
          <div className="max-w-7xl mx-auto flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
              <span>
                <strong>Veterinarian Dispatched:</strong> On-site emergency visit accepted for <strong>{dispatchedAlert.farmId}</strong>.
              </span>
            </div>
            <span className="text-emerald-300 font-mono text-[11px] bg-emerald-950 px-2 py-0.5 rounded">
              ETA: ~25 Mins
            </span>
          </div>
        </div>
      )}

      {/* Main View Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        
        {/* ========================================================================= */}
        {/* FARMER DASHBOARD ROLE VIEW                                                */}
        {/* ========================================================================= */}
        {role === 'farmer' && (
          <div className="space-y-6">
            
            {/* Dashboard Summary Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              
              {/* Health Risk Card */}
              <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
                <div>
                  <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">Flock Health Index</p>
                  <div className="flex items-baseline space-x-2 mt-1">
                    <span className="text-3xl font-extrabold text-slate-900">
                      {analysisResult
                        ? analysisResult.risk_level === 'LOW' ? '85' : analysisResult.risk_level === 'MODERATE' ? '62' : '35'
                        : '72'}
                    </span>
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full border ${
                      analysisResult?.risk_level === 'HIGH' 
                        ? 'text-red-600 bg-red-50 border-red-200' 
                        : analysisResult?.risk_level === 'LOW'
                        ? 'text-emerald-600 bg-emerald-50 border-emerald-200'
                        : 'text-amber-600 bg-amber-50 border-amber-200'
                    }`}>
                      {analysisResult?.risk_level === 'HIGH' ? 'High Risk' : analysisResult?.risk_level === 'LOW' ? 'Low Risk' : 'Moderate Risk'}
                    </span>
                  </div>
                  <p className="text-xs text-slate-400 mt-1">Based on visual movement density</p>
                </div>
                <div className="w-12 h-12 rounded-2xl bg-amber-50 flex items-center justify-center text-amber-600 border border-amber-100">
                  <Activity className="w-6 h-6" />
                </div>
              </div>

              {/* Active Anomalies Card */}
              <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
                <div>
                  <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">Active Anomalies</p>
                  <div className="flex items-baseline space-x-2 mt-1">
                    <span className="text-3xl font-extrabold text-slate-900">
                      {alerts.filter(a => a.status !== 'DISMISSED').length}
                    </span>
                    <span className="text-xs font-semibold text-red-600 bg-red-50 px-2 py-0.5 rounded-full border border-red-200">
                      Requires Check
                    </span>
                  </div>
                  <p className="text-xs text-slate-400 mt-1">{alerts.filter(a => a.status === 'PENDING').length} high urgency alert logged</p>
                </div>
                <div className="w-12 h-12 rounded-2xl bg-red-50 flex items-center justify-center text-red-600 border border-red-100">
                  <AlertTriangle className="w-6 h-6" />
                </div>
              </div>

              {/* Local AI Engine Status */}
              <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
                <div>
                  <p className="text-xs font-medium text-slate-500 uppercase tracking-wider">AI Local Engine</p>
                  <div className="flex items-center space-x-2 mt-1">
                    <span className="text-lg font-bold text-slate-900">Gemma 4 12B</span>
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full border flex items-center gap-1 ${
                      backendStatus === 'connected' 
                        ? 'text-emerald-700 bg-emerald-50 border-emerald-200' 
                        : 'text-amber-700 bg-amber-50 border-amber-200'
                    }`}>
                      <span className={`w-1.5 h-1.5 rounded-full ${backendStatus === 'connected' ? 'bg-emerald-500' : 'bg-amber-500'}`}></span>
                      {backendStatus === 'connected' ? 'Active' : 'Demo Mode'}
                    </span>
                  </div>
                  <p className="text-xs text-slate-400 mt-1">Zero cloud latency • Private</p>
                </div>
                <div className="w-12 h-12 rounded-2xl bg-emerald-50 flex items-center justify-center text-emerald-600 border border-emerald-100">
                  <Cpu className="w-6 h-6" />
                </div>
              </div>
            </div>

            {/* Image Analysis Section */}
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 space-y-6">
              
              {/* Header & Mode Selector */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-5">
                <div>
                  <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
                    <Camera className="w-5 h-5 text-emerald-600" />
                    Flock Surveillance & Anomaly Detection
                  </h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Upload current flock images or perform comparative visual delta analysis.
                  </p>
                </div>

                {/* Analysis Mode Toggle */}
                <div className="flex items-center space-x-3">
                  <div className="bg-slate-100 p-1 rounded-xl flex items-center border border-slate-200 text-xs">
                    <button
                      onClick={() => setComparisonMode(false)}
                      className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
                        !comparisonMode ? 'bg-white text-slate-900 shadow-sm font-semibold' : 'text-slate-600 hover:text-slate-900'
                      }`}
                    >
                      Single Image
                    </button>
                    <button
                      onClick={() => setComparisonMode(true)}
                      className={`px-3 py-1.5 rounded-lg font-medium transition-all ${
                        comparisonMode ? 'bg-white text-slate-900 shadow-sm font-semibold' : 'text-slate-600 hover:text-slate-900'
                      }`}
                    >
                      Before vs After
                    </button>
                  </div>
                </div>
              </div>

              {/* Demo Loaders Bar */}
              <div className="bg-slate-50 p-3 rounded-xl border border-slate-200/80 flex flex-wrap items-center justify-between gap-3 text-xs">
                <div className="flex items-center space-x-2 text-slate-600">
                  <Sliders className="w-4 h-4 text-emerald-600" />
                  <span className="font-semibold text-slate-700">Hackathon Pitch Quick-Demos:</span>
                </div>
                <div className="flex items-center space-x-2">
                  <button
                    onClick={() => loadDemo('anomaly')}
                    className="px-3 py-1.5 bg-amber-100 hover:bg-amber-200 text-amber-900 font-semibold rounded-lg border border-amber-300 transition-colors flex items-center gap-1.5"
                  >
                    <AlertTriangle className="w-3.5 h-3.5 text-amber-700" />
                    Load High-Risk Anomaly Case
                  </button>
                  <button
                    onClick={() => loadDemo('healthy')}
                    className="px-3 py-1.5 bg-emerald-100 hover:bg-emerald-200 text-emerald-900 font-semibold rounded-lg border border-emerald-300 transition-colors flex items-center gap-1.5"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-700" />
                    Load Healthy Baseline Case
                  </button>
                </div>
              </div>

              {/* Image Upload Area */}
              <div className={`grid gap-6 ${comparisonMode ? 'grid-cols-1 md:grid-cols-2' : 'grid-cols-1'}`}>
                
                {/* Previous/Healthy Reference Upload Box */}
                {comparisonMode && (
                  <div className="space-y-2">
                    <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider">
                      1. Reference Image (Previous / Healthy)
                    </label>
                    <div className="relative group border-2 border-dashed border-slate-300 hover:border-emerald-500 rounded-2xl p-4 text-center bg-slate-50 hover:bg-emerald-50/30 transition-all min-h-[220px] flex flex-col items-center justify-center">
                      {prevImage ? (
                        <div className="relative w-full h-48 rounded-xl overflow-hidden border border-slate-200">
                          <img src={prevImage} alt="Previous Flock" className="w-full h-full object-cover" />
                          <button
                            onClick={(e) => { e.stopPropagation(); setPrevImage(null); setPrevFile(null); }}
                            className="absolute top-2 right-2 bg-slate-900/80 hover:bg-slate-900 text-white p-1.5 rounded-full backdrop-blur-sm transition-colors"
                          >
                            <X className="w-4 h-4" />
                          </button>
                          <span className="absolute bottom-2 left-2 bg-slate-900/70 text-white text-[10px] font-mono px-2 py-0.5 rounded">
                            Baseline
                          </span>
                        </div>
                      ) : (
                        <div className="space-y-2">
                          <div className="w-10 h-10 rounded-full bg-slate-200/80 flex items-center justify-center text-slate-500 mx-auto group-hover:bg-emerald-100 group-hover:text-emerald-600 transition-colors">
                            <UploadCloud className="w-5 h-5" />
                          </div>
                          <div className="text-xs">
                            <span className="font-semibold text-emerald-600">Click to upload</span> or drag baseline image
                          </div>
                          <p className="text-[11px] text-slate-400">JPG, PNG up to 10MB</p>
                        </div>
                      )}
                      <input 
                        type="file" 
                        accept="image/*"
                        className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                        onChange={handlePrevFileUpload}
                      />
                    </div>
                  </div>
                )}

                {/* Current Flock Upload Box */}
                <div className="space-y-2">
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider">
                    {comparisonMode ? '2. Observation Image (Current Flock)' : 'Observation Flock Image'}
                  </label>
                  <div className="relative group border-2 border-dashed border-slate-300 hover:border-emerald-500 rounded-2xl p-4 text-center bg-slate-50 hover:bg-emerald-50/30 transition-all min-h-[220px] flex flex-col items-center justify-center">
                    {currImage ? (
                      <div className="relative w-full h-48 rounded-xl overflow-hidden border border-slate-200">
                        <img src={currImage} alt="Current Flock" className="w-full h-full object-cover" />
                        <button
                          onClick={(e) => { e.stopPropagation(); setCurrImage(null); setCurrFile(null); }}
                          className="absolute top-2 right-2 bg-slate-900/80 hover:bg-slate-900 text-white p-1.5 rounded-full backdrop-blur-sm transition-colors"
                        >
                          <X className="w-4 h-4" />
                        </button>
                        <span className="absolute bottom-2 left-2 bg-slate-900/70 text-white text-[10px] font-mono px-2 py-0.5 rounded">
                          Observation
                        </span>
                      </div>
                    ) : (
                      <div className="space-y-2">
                        <div className="w-10 h-10 rounded-full bg-slate-200/80 flex items-center justify-center text-slate-500 mx-auto group-hover:bg-emerald-100 group-hover:text-emerald-600 transition-colors">
                          <UploadCloud className="w-5 h-5" />
                        </div>
                        <div className="text-xs">
                          <span className="font-semibold text-emerald-600">Click to upload</span> or drag flock observation
                        </div>
                        <p className="text-[11px] text-slate-400">JPG, PNG up to 10MB</p>
                      </div>
                    )}
                    <input 
                      type="file" 
                      accept="image/*"
                      className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                      onChange={handleCurrFileUpload}
                    />
                  </div>
                </div>
              </div>

              {/* Action Submit Trigger Buttons */}
              <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
                <div className="flex items-center text-xs text-slate-500">
                  <span className="inline-block w-2 h-2 rounded-full bg-emerald-500 mr-2 animate-pulse"></span>
                  <span>Local AI: Gemma 4 12B via Ollama</span>
                </div>

                <div className="flex items-center gap-3">
                  {/* Instant Demo Test button */}
                  <button
                    onClick={() => runAnalysis(true)}
                    disabled={!currImage || analyzing}
                    title="Run instant 1-second analysis with demo data (ideal for testing UI flows quickly)"
                    className={`px-4 py-2.5 rounded-xl text-xs font-semibold border transition-all flex items-center space-x-1.5 ${
                      !currImage || analyzing
                        ? 'border-slate-200 text-slate-400 cursor-not-allowed'
                        : 'border-slate-300 text-slate-700 bg-white hover:bg-slate-50 hover:border-slate-400 active:scale-98 shadow-sm'
                    }`}
                  >
                    <Zap className="w-3.5 h-3.5 text-amber-500 fill-amber-500" />
                    <span>Instant Demo Test (⚡ ~1s)</span>
                  </button>

                  {/* Real Gemma 4 12B Live inference button */}
                  <button
                    onClick={() => runAnalysis(false)}
                    disabled={!currImage || analyzing}
                    className={`px-6 py-2.5 rounded-xl text-xs font-bold shadow-lg transition-all flex items-center space-x-2 ${
                      !currImage || analyzing
                        ? 'bg-slate-200 text-slate-400 cursor-not-allowed shadow-none'
                        : 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-900/20 active:scale-98'
                    }`}
                  >
                    {analyzing ? (
                      <>
                        <RefreshCw className="w-4 h-4 animate-spin text-white" />
                        <span>Analyzing with Live Gemma 4... ({elapsedSeconds}s)</span>
                      </>
                    ) : (
                      <>
                        <Eye className="w-4 h-4" />
                        <span>{comparisonMode ? 'Compare Images (Live Gemma 4)' : 'Analyze Image (Live Gemma 4)'}</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Analysis Progress Visualization */}
              {analyzing && (
                <div className="bg-slate-900 text-slate-100 p-5 rounded-2xl border border-slate-800 space-y-4 animate-fade-in shadow-xl">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-800 pb-3">
                    <div className="flex items-center space-x-2">
                      <Cpu className="w-5 h-5 text-emerald-400 animate-pulse" />
                      <span className="text-xs font-mono font-bold text-emerald-400 uppercase tracking-widest">
                        {useBackendAPI ? 'Gemma 4 12B Vision Pipeline Active' : 'Demo Analysis Engine Active'}
                      </span>
                      <span className="text-[11px] font-mono bg-slate-800 text-emerald-300 px-2 py-0.5 rounded-full border border-slate-700">
                        ⏱️ {elapsedSeconds}s elapsed
                      </span>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={skipToDemoResult}
                        className="flex items-center space-x-1 px-2.5 py-1 rounded-lg text-[11px] font-medium bg-amber-500/20 border border-amber-500/40 text-amber-300 hover:bg-amber-500/30 transition-colors"
                        title="Skip waiting for local GPU and view structured result immediately"
                      >
                        <Zap className="w-3 h-3 fill-amber-300" />
                        <span>Skip & View Result Now</span>
                      </button>
                      <span className="text-xs font-mono text-slate-400 hidden sm:inline">Model: gemma4:12b</span>
                    </div>
                  </div>

                  <p className="text-xs text-slate-400">
                    ⚡ Gemma 4 12B is processing visual multimodal tokens locally on your GPU/CPU via Ollama. 
                    Local vision inference typically takes <strong className="text-slate-200">25–45 seconds</strong>. No cloud servers are contacted.
                  </p>

                  {/* Visual Progress Bar with Live ETA */}
                  <div className="space-y-1.5 pt-1">
                    <div className="flex justify-between text-[11px] font-mono">
                      <span className="text-emerald-400 flex items-center gap-1.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping"></span>
                        Neural network computing on local GPU...
                      </span>
                      <span className="text-slate-400 font-semibold">
                        {Math.min(95, Math.max(10, Math.floor((elapsedSeconds / 40) * 100)))}% • ~{Math.max(5, 40 - elapsedSeconds)}s est. remaining
                      </span>
                    </div>
                    <div className="w-full bg-slate-800 rounded-full h-2.5 overflow-hidden border border-slate-700/60 shadow-inner">
                      <div 
                        className="bg-gradient-to-r from-emerald-600 via-emerald-400 to-teal-300 h-full rounded-full transition-all duration-500 ease-out shadow-lg shadow-emerald-500/30"
                        style={{ width: `${Math.min(95, Math.max(10, Math.floor((elapsedSeconds / 40) * 100)))}%` }}
                      />
                    </div>
                  </div>

                  {/* Progress Steps */}
                  <div className="space-y-2.5">
                    <div className="flex items-center space-x-3 text-xs">
                      <div className={`w-5 h-5 rounded-full flex items-center justify-center font-mono text-[10px] ${
                        analysisStep >= 1 ? 'bg-emerald-500 text-slate-950 font-bold' : 'bg-slate-800 text-slate-500'
                      }`}>1</div>
                      <span className={analysisStep >= 1 ? 'text-slate-100 font-medium' : 'text-slate-500'}>
                        Loading local tensor tensors into vision buffer...
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 text-xs">
                      <div className={`w-5 h-5 rounded-full flex items-center justify-center font-mono text-[10px] ${
                        analysisStep >= 2 ? 'bg-emerald-500 text-slate-950 font-bold' : 'bg-slate-800 text-slate-500'
                      }`}>2</div>
                      <span className={analysisStep >= 2 ? 'text-slate-100 font-medium' : 'text-slate-500'}>
                        Gemma examining flock posture & spatial distribution patterns...
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 text-xs">
                      <div className={`w-5 h-5 rounded-full flex items-center justify-center font-mono text-[10px] ${
                        analysisStep >= 3 ? 'bg-emerald-500 text-slate-950 font-bold' : 'bg-slate-800 text-slate-500'
                      }`}>3</div>
                      <span className={analysisStep >= 3 ? 'text-slate-100 font-medium' : 'text-slate-500'}>
                        {comparisonMode ? 'Computing structural changes against reference baseline...' : 'Detecting visual anomaly features...'}
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 text-xs">
                      <div className={`w-5 h-5 rounded-full flex items-center justify-center font-mono text-[10px] ${
                        analysisStep >= 4 ? 'bg-emerald-500 text-slate-950 font-bold' : 'bg-slate-800 text-slate-500'
                      }`}>4</div>
                      <span className={analysisStep >= 4 ? 'text-slate-100 font-medium' : 'text-slate-500'}>
                        Structuring health risk assessment JSON output...
                      </span>
                    </div>
                  </div>
                </div>
              )}

              {/* Analysis Results */}
              {analysisResult && !analyzing && (
                <div className="mt-8 border-t border-slate-200 pt-6 space-y-6 animate-fade-in">
                  
                  {/* Result Header Badge */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-50 p-4 rounded-2xl border border-slate-200">
                    <div>
                      <span className="text-[11px] font-bold uppercase tracking-wider text-slate-500">
                        AI Visual Assessment Output
                      </span>
                      <h3 className="text-base font-extrabold text-slate-900 mt-0.5">
                        {analysisResult.summary}
                      </h3>
                    </div>

                    {/* Risk Badge */}
                    <div className="shrink-0">
                      {analysisResult.risk_level === 'HIGH' && (
                        <span className="inline-flex items-center px-3.5 py-1.5 rounded-full text-xs font-bold bg-red-100 text-red-800 border border-red-300 shadow-sm">
                          <AlertTriangle className="w-4 h-4 mr-1.5 text-red-600" />
                          HIGH ANOMALY RISK
                        </span>
                      )}
                      {analysisResult.risk_level === 'CRITICAL' && (
                        <span className="inline-flex items-center px-3.5 py-1.5 rounded-full text-xs font-bold bg-red-600 text-white shadow-sm">
                          <AlertCircle className="w-4 h-4 mr-1.5" />
                          CRITICAL RISK
                        </span>
                      )}
                      {analysisResult.risk_level === 'MODERATE' && (
                        <span className="inline-flex items-center px-3.5 py-1.5 rounded-full text-xs font-bold bg-amber-100 text-amber-800 border border-amber-300 shadow-sm">
                          <AlertCircle className="w-4 h-4 mr-1.5 text-amber-600" />
                          MODERATE ANOMALY RISK
                        </span>
                      )}
                      {analysisResult.risk_level === 'LOW' && (
                        <span className="inline-flex items-center px-3.5 py-1.5 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 border border-emerald-300 shadow-sm">
                          <ShieldCheck className="w-4 h-4 mr-1.5 text-emerald-600" />
                          LOW ANOMALY RISK
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Two Column Grid: Observations & Evidence */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    
                    {/* Visual Observations List */}
                    <div className="space-y-3">
                      <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                        <Eye className="w-4 h-4 text-emerald-600" />
                        Detected Observations
                      </h4>
                      <div className="space-y-2.5">
                        {analysisResult.observations.map((obs, idx) => (
                          <div key={idx} className="bg-white p-3.5 rounded-xl border border-slate-200 shadow-sm">
                            <div className="flex items-center justify-between">
                              <span className="text-xs font-bold text-slate-900">{obs.title}</span>
                              <span className={`text-[10px] font-semibold uppercase px-2 py-0.5 rounded ${
                                obs.severity === 'high' ? 'bg-red-100 text-red-700' :
                                obs.severity === 'medium' ? 'bg-amber-100 text-amber-700' : 'bg-slate-100 text-slate-600'
                              }`}>
                                {obs.severity} severity
                              </span>
                            </div>
                            <p className="text-xs text-slate-600 mt-1">{obs.description}</p>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Evidence Checklist & Recommended Action */}
                    <div className="space-y-4">
                      {/* Evidence */}
                      <div className="space-y-2">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                          <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                          Supporting Evidence
                        </h4>
                        <div className="bg-slate-50 p-3.5 rounded-xl border border-slate-200 space-y-1.5">
                          {analysisResult.evidence.map((item, idx) => (
                            <div key={idx} className="flex items-center text-xs text-slate-700 space-x-2">
                              <span className="text-emerald-600 font-bold">✓</span>
                              <span>{item}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Recommended Action */}
                      <div className="space-y-2">
                        <h4 className="text-xs font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
                          <AlertTriangle className="w-4 h-4 text-amber-600" />
                          Recommended Action
                        </h4>
                        <div className="bg-amber-50/80 p-3.5 rounded-xl border border-amber-200 text-xs text-amber-900 font-medium">
                          {analysisResult.recommended_action}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* AI Uncertainty & Safety Disclaimer */}
                  <div className="bg-slate-100 p-3.5 rounded-xl border border-slate-200 flex items-start space-x-2.5 text-xs text-slate-600">
                    <Info className="w-4 h-4 text-slate-500 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-bold text-slate-700">Safety & Uncertainty Note: </span>
                      {analysisResult.uncertainty} This system provides non-clinical decision support.
                    </div>
                  </div>

                  {/* Action Trigger Button for Vet Emergency */}
                  <div className="flex flex-col sm:flex-row items-center justify-between pt-2 gap-3 bg-slate-900 text-white p-4 rounded-2xl">
                    <div>
                      <h4 className="text-xs font-bold text-white uppercase tracking-wider">
                        Require Veterinary Consultation?
                      </h4>
                      <p className="text-xs text-slate-400 mt-0.5">
                        Push this structured anomaly package directly to the Emergency Veterinary Dispatch queue.
                      </p>
                    </div>
                    <button
                      onClick={triggerVetAlert}
                      className="w-full sm:w-auto px-5 py-2.5 rounded-xl bg-red-600 hover:bg-red-700 text-white font-bold text-xs shadow-lg shadow-red-950/50 transition-all flex items-center justify-center space-x-2 shrink-0"
                    >
                      <Stethoscope className="w-4 h-4" />
                      <span>Dispatch Urgent Vet Request</span>
                    </button>
                  </div>

                </div>
              )}

            </div>
          </div>
        )}

        {/* ========================================================================= */}
        {/* VETERINARY DASHBOARD ROLE VIEW                                            */}
        {/* ========================================================================= */}
        {role === 'vet' && (
          <div className="space-y-6">
            
            {/* Vet Header */}
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="flex items-center space-x-3">
                <div className="w-12 h-12 rounded-2xl bg-emerald-100 text-emerald-800 flex items-center justify-center font-bold">
                  <Stethoscope className="w-6 h-6" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900">Veterinary Emergency Dispatch Console</h2>
                  <p className="text-xs text-slate-500">Triage incoming local AI anomaly reports and dispatch on-site teams.</p>
                </div>
              </div>

              {/* Status Badge */}
              <div className="flex items-center space-x-2 bg-slate-100 px-3 py-1.5 rounded-xl border border-slate-200 text-xs">
                <span className="font-semibold text-slate-700">Incoming Requests:</span>
                <span className="px-2 py-0.5 bg-red-600 text-white font-bold rounded-full text-[11px]">
                  {alerts.filter(a => a.status === 'PENDING').length}
                </span>
              </div>
            </div>

            {/* Emergency Alert List Container */}
            <div className="space-y-4">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-600">
                Active Farm Emergency Alerts
              </h3>

              {alerts.length === 0 ? (
                <div className="bg-white p-12 rounded-2xl border border-slate-200 text-center space-y-2">
                  <CheckCircle2 className="w-10 h-10 text-emerald-500 mx-auto" />
                  <p className="text-sm font-bold text-slate-800">No Pending Emergency Alerts</p>
                  <p className="text-xs text-slate-400">All regional farm reports have been triaged or dispatched.</p>
                </div>
              ) : (
                alerts.map((alertItem) => (
                  <div 
                    key={alertItem.id} 
                    className={`bg-white rounded-2xl border transition-all p-5 shadow-sm space-y-4 ${
                      alertItem.status === 'DISPATCHED' 
                        ? 'border-emerald-300 bg-emerald-50/20' 
                        : alertItem.status === 'DISMISSED'
                        ? 'border-slate-200 opacity-60'
                        : 'border-red-200 hover:border-red-300'
                    }`}
                  >
                    {/* Top Row: Farm ID & Status */}
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 pb-3">
                      <div className="flex items-center space-x-3">
                        <span className="font-mono text-xs font-bold bg-slate-900 text-white px-2.5 py-1 rounded-lg">
                          {alertItem.id}
                        </span>
                        <div>
                          <h4 className="text-sm font-extrabold text-slate-900">{alertItem.farmId}</h4>
                          <p className="text-[11px] text-slate-500 flex items-center gap-1 mt-0.5">
                            <MapPin className="w-3 h-3 text-slate-400" />
                            {alertItem.location} • <Clock className="w-3 h-3 text-slate-400" /> {alertItem.timestamp}
                          </p>
                        </div>
                      </div>

                      {/* Urgency Badge */}
                      <div>
                        {alertItem.status === 'DISPATCHED' ? (
                          <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-800 border border-emerald-300">
                            <CheckCircle2 className="w-3.5 h-3.5 mr-1 text-emerald-600" />
                            Veterinarian Dispatched
                          </span>
                        ) : alertItem.status === 'DISMISSED' ? (
                          <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold bg-slate-100 text-slate-600">
                            Dismissed
                          </span>
                        ) : (
                          <span className="inline-flex items-center px-3 py-1 rounded-full text-xs font-bold bg-red-100 text-red-800 border border-red-300">
                            <AlertTriangle className="w-3.5 h-3.5 mr-1 text-red-600" />
                            {alertItem.riskLevel} ANOMALY URGENCY
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Middle Row: Content & Image Previews */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      {/* Left: Summary & Evidence */}
                      <div className="md:col-span-2 space-y-3">
                        <div className="bg-slate-50 p-3 rounded-xl border border-slate-200">
                          <p className="text-xs font-bold text-slate-800">Gemma Visual Findings:</p>
                          <p className="text-xs text-slate-600 mt-0.5">{alertItem.summary}</p>
                        </div>

                        <div className="space-y-1">
                          <p className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                            Key Visual Indicators:
                          </p>
                          <div className="flex flex-wrap gap-1.5">
                            {alertItem.evidence.map((ev, i) => (
                              <span key={i} className="text-[11px] bg-slate-100 text-slate-700 px-2.5 py-0.5 rounded-md border border-slate-200">
                                {ev}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>

                      {/* Right: Attached Visual Evidence Proof */}
                      <div className="space-y-1">
                        <p className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                          Attached Proof Images:
                        </p>
                        <div className="grid grid-cols-2 gap-2">
                          <div className="relative h-24 rounded-lg overflow-hidden border border-slate-200">
                            <img src={alertItem.prevImg} alt="Baseline" className="w-full h-full object-cover" />
                            <span className="absolute bottom-1 left-1 bg-slate-900/80 text-white text-[9px] px-1 rounded">
                              Baseline
                            </span>
                          </div>
                          <div className="relative h-24 rounded-lg overflow-hidden border border-slate-200">
                            <img src={alertItem.currImg} alt="Current" className="w-full h-full object-cover" />
                            <span className="absolute bottom-1 left-1 bg-red-900/80 text-white text-[9px] px-1 rounded">
                              Anomaly
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Bottom Action Bar */}
                    {alertItem.status === 'PENDING' && (
                      <div className="flex flex-col sm:flex-row items-center justify-end gap-2 pt-2 border-t border-slate-100">
                        <button
                          onClick={() => handleAlertAction(alertItem.id, 'DISMISSED')}
                          className="w-full sm:w-auto px-4 py-2 rounded-xl text-xs font-semibold text-slate-600 hover:bg-slate-100 transition-colors"
                        >
                          Dismiss Alert
                        </button>
                        <button
                          onClick={() => handleAlertAction(alertItem.id, 'DISPATCHED')}
                          className="w-full sm:w-auto px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-md shadow-emerald-900/20 transition-all flex items-center justify-center space-x-1.5"
                        >
                          <CheckCircle2 className="w-4 h-4" />
                          <span>Accept Visit & Dispatch Veterinarian</span>
                        </button>
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>

          </div>
        )}

      </main>

      {/* Footer */}
      <footer className="bg-white border-t border-slate-200 mt-12 py-6 text-xs text-slate-500">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center space-x-2">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span className="font-semibold text-slate-700">FlockGuard Hackathon Architecture</span>
            <span>•</span>
            <span>Gemma 4 12B Vision on Ollama</span>
          </div>
          <div className="text-slate-400 text-[11px]">
            Privacy Preserving • On-Farm Offline AI Support • Not a Clinical Diagnosis
          </div>
        </div>
      </footer>
    </div>
  );
}
